### ISSUE TITLE
Provide real-world example

### ISSUE THREAD

**Issue by ErinsMatthew** [neilff/angular-menu-aim#5]
I am very interested in this project, as I am hoping to use jQuery-menu-aim in an upcoming AngularJS project.  I would like to recommend that you consider replicating the example provided by the original author using your AngularJS version.
- https://github.com/kamens/jQuery-menu-aim/blob/master/example/example.html
- https://rawgithub.com/kamens/jQuery-menu-aim/master/example/example.html

I am willing to work through and contribute such an example if you prefer.

**Comment by neilff** [comment]
Sure feel free to submit a PR. The original package was used in a project and the example reflects that. If you want to update the example I'll gladly accept a PR.
